# Generated by Codex on 2026-07-07

from django.db import migrations, models


def backfill_inactive_seconds(apps, schema_editor):
    TimeEntry = apps.get_model('time_tracking', 'TimeEntry')
    WorkSession = apps.get_model('time_tracking', 'WorkSession')
    TimeEntry.objects.filter(inactive_seconds=0, inactive_minutes__gt=0).update(
        inactive_seconds=models.F('inactive_minutes') * 60,
    )
    WorkSession.objects.filter(inactive_seconds=0, inactive_minutes__gt=0).update(
        inactive_seconds=models.F('inactive_minutes') * 60,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='inactive_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='inactive_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_inactive_seconds, migrations.RunPython.noop),
    ]
