# Generated by Django 6.0.6 on 2026-07-07 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hourlyrate',
            constraint=models.UniqueConstraint(fields=('user', 'valid_from'), name='unique_hourly_rate_per_user_date'),
        ),
    ]
