# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeecharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecharge',
            old_name='starts_on',
            new_name='starts_at',
        ),
        migrations.AlterField(
            model_name='employeecharge',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeecharge',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Jednorazowa'), ('monthly', 'Miesięczna')], default='once', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='employeecharge',
            options={'ordering': ['-starts_at', '-created_at']},
        ),
    ]
