# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeecharge_starts_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecharge',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='employeecharge',
            name='recurrence',
        ),
    ]
